### ISSUE TITLE
Incompatibility with AWS Lambda

### ISSUE THREAD

**Issue by armeenm** [nlewo/nix2container#54]
Hi, I have been trying to build a container with nix2container to use with AWS Lambda. Unfortunately, attempting to create a Lambda function with such a container results in the error `MissingParentDirectory: Parent directory does not exist for file: /nix/store/<some folder in the container>`. The same container produced with dockerTools.buildImage loads successfully.

I have created https://github.com/armeenm/n2c-lambda to help reproduce this issue. Please let me know if you need anything else to debug.

Thanks!

**Comment by nlewo** [comment]
Hello @armeenm 

I think this is because these directories are added at the end of the tar stream. I'm currently refactoring this part of nix2container (to solve another issue) and these directories will be created at the beginning of the tar stream.

I will provide an update here once a PR has been submitted.

Thanks for the report!

**Comment by nlewo** [comment]
Should be fixed by: https://github.com/nlewo/nix2container/pull/55

**Comment by nlewo** [comment]
@armeenm Cool, thx for the quick feedback!

**Comment by nlewo** [comment]
Fix by #55.
