### ISSUE TITLE
nixDatabase contains paths which are not part of the image

### ISSUE THREAD

**Issue by kolloch** [nlewo/nix2container#94]
In [` nixDatabase = makeNixDatabase ([configFile] ++ copyToRootList ++ layers);`](https://github.com/nlewo/nix2container/blob/9d7f33ef0058f4df4c0912025f43c758a3289d76/default.nix#L363) store paths are added to the nixDatabase which are actually not in the image itself -- i.e. the image configurations.

That leads to errors when the resulting image is used to build itself again. The database will claim that the config is already in the store but then it cannot be opened.

**Comment by nlewo** [comment]
This is because the configuration file path is [explicitly ignored](https://github.com/nlewo/containers-image-nix/blob/9d7f33ef0058f4df4c0912025f43c758a3289d76/default.nix#L386) to avoid building a new layer when a configuration parameter is updated. We need to take the configuration file into account in order to create a layer with its closure but we don't need to put the configuration into a layer since this configuration file already part of the OCI image itself.

So, I htink we would have two options:
- improve `makeNixDatabase` to ignore the configuration file path (better but harder)
- add the configuration file into the layer when the `initializeNixDatabase=true` (more simple but not really nice :/)

**Comment by kolloch** [comment]
Even though the config files are tiny, I also like the first approach more.

So I guess it is about filtering the storepaths specified in the `ignore` setting of the layers? Is an "ignored" path only ignored in the same layer or globally? I think only in the same layer would work as expected but would also be so much more complicated: Then we would need to calculate the closure of each layer and subtract the ignore path(s) and then create the union.
